version: "3.2"
services:
  goserver:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment: 
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - HASH_SALT=${HASH_SALT}
      - PORT=${PORT}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - "${PORT}:${PORT}"
    restart: always
    networks: 
      - backend
  postgres:
    image: 'postgres:12.2-alpine'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose: 
      - "5432"
    volumes:
      - ./docker/postgres/entrypoint/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks: 
      - backend
  redis:
    image: 'redis:5.0.8'
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes: 
      - ./docker/redis/data:/data
    networks: 
      - backend
networks:
  backend:
